postsubmits:
  - name: post-banka-2-frontend-postsubmits
    labels:
      preset-harbor-robot-push: "true"
    decorate: true
    always_run: true
    branches:
      - ^main$
    extra_refs:
      - org: RAF-SI-2022
        repo: Banka-2-Infrastructure
        base_ref: main
        path_alias: "infra"
    spec:
      serviceAccountName: prow-admin
      containers:
        - image: harbor.k8s.elab.rs/base-images/base:java-17-node-18-docker
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              
              #####################################
              # Define environment/namespace vars #
              #####################################
              
              export ENV="prod"
              export SIDE="frontend"
              export NAMESPACE="banka-2-$ENV"
              export SERVICES="frontend-prod"
              
              ##############
              # Call setup #
              ##############
  
              start-docker.sh
              docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD harbor.k8s.elab.rs
              
              INFRA_SRC=/home/prow/go/src/infra/
              rsync -av --exclude='.git' ${INFRA_SRC} .
              
              chmod +x kubernetes/upgrade.sh
              bash kubernetes/upgrade.sh --update

          securityContext:
            privileged: true
          imagePullPolicy: Always