postsubmits:
  - name: post-banka-2-frontend-users-prod-postsubmits
    labels:
      preset-harbor-robot-push: "true"
    decorate: true
    always_run: true
    branches:
      - ^main$
    spec:
      serviceAccountName: prow-admin
      containers:
        - image: harbor.k8s.elab.rs/base-images/base:java-17-node-18-docker
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              ################################
              # Build and push Docker images #
              ################################

              start-docker.sh
              docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD harbor.k8s.elab.rs

              commit_hash=$(git rev-parse HEAD)
              tag_name=$(git tag --points-at HEAD)
              
              services="frontend"
              services=$(echo $services | xargs)

              image_tags="latest"
              image_tags="latest-stable"
              image_tags+=" ${commit_hash}"
              image_tags+=" ${tag_name}"
              image_tags=$(echo $image_tags | xargs)

              docker build -t harbor.k8s.elab.rs/banka-2/users:builder -f ./docker/users.Dockerfile .
              docker build -t harbor.k8s.elab.rs/banka-2/otc:builder -f ./docker/otc.Dockerfile .
              docker build -t harbor.k8s.elab.rs/banka-2/main:builder -f ./docker/main.Dockerfile .

              for $service in $services
              do
                for tag in $image_tags
                do
                  docker build -t harbor.k8s.elab.rs/banka-2/$service:builder -f ./docker/$service.Dockerfile .
                  docker tag harbor.k8s.elab.rs/banka-2/$service:builder harbor.k8s.elab.rs/banka-2/$service:$tag
                  docker push harbor.k8s.elab.rs/banka-2/$service:$tag
                done
              done
              
              ########################
              # Deploy to production #
              ########################
              
              namespace="banka-2-prod"
              domainPrefix="banka-2"
              imageVer="$commit_hash"
              
              cd kubernetes
              helm upgrade banka-2-prod . --reuse-values \
                --set namespace=$namespace \
                --set domainPrefix=$domainPrefix \
                --set frontend.imageVer=$imageVer \
                -n banka-2-prod

          securityContext:
            privileged: true
          imagePullPolicy: Always